version: '2'
services:
  inventory-app:
    image: bangbangman/shop.demo.inventory
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    ports:
      - 8081:8081
  inventory-mongodb:
    extends:
      file: mongodb.yml
      service: inventory-mongodb