version: '2'
services:
  orders-app:
    image: bangbangman/shop.demo.orders
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    ports:
      - 8082:8082
  orders-mongodb:
    extends:
      file: mongodb.yml
      service: orders-mongodb
  orders-axon:
    extends:
      file: axon.yml
      service: orders-axon